name: Hourly Report

on:
  schedule:
    - cron: '0 1 * * *' # 每天 UTC 时间1点（对应北京时间早上9点）
    - cron: '0 4 * * *' # 每天 UTC 时间1点（对应北京时间早上12点）
    - cron: '0 13 * * *' # 每天 UTC 时间13点（对应北京时间晚上9点）
  workflow_dispatch: # 手动触发
  
jobs:
  report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install node-fetch

    - name: Run script
      run: node checkBandwidth.js
      env:
        DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
