name: daily_report

on:
  schedule:
    - cron: '0 0-16 * * *' # 每天  东八  从8点到24点 的每小时触发一次
  workflow_dispatch: # 手动触发
  
jobs:
  report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install node-fetch

    - name: Run script
      run: node checkBandwidth.js
      env:
        DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
        JMS_API: ${{ secrets.JMS_API }}
